const taylorSongs = [
    "...Ready for It?",
    "End Game",
    "I Did Something Bad",
    "Don't Blame Me",
    "Delicate",
    "Look What You Made Me Do",
    "So It Goes...",
    "Gorgeous",
    "Getaway Car",
    "King of My Heart",
    "Dancing with Our Hands Tied",
    "Dress",
    "This Is Why We Can't Have Nice Things",
    "Call It What You Want",
    "New Year's Day",
    "Tim McGraw",
    "Picture To Burn",
    "Teardrops On My Guitar",
    "A Place In This World",
    "Cold As You",
    "The Outside",
    "Tied Together With A Smile",
    "Stay Beautiful",
    "Should've Said No",
    "Mary's Song (Oh My My My)",
    "Our Song",
    "I'm Only Me When I'm With You",
    "Invisible",
    "Perfectly Good Heart",
    "willow",
    "champagne problems",
    "gold rush",
    "'tis the damn season",
    "tolerate it",
    "no body, no crime",
    "happiness",
    "dorothea",
    "coney island",
    "ivy",
    "cowboy like me",
    "long story short",
    "marjorie",
    "closure",
    "evermore",
    "right where you left me",
    "it's time to go",
    "Mine",
    "Sparks Fly",
    "Forever & Always",
    "Change",
    "I Forgot That You Existed",
    "Cruel Summer",
    "Lover",
    "The Man",
    "The Archer",
    "I Think He Knows",
    "Miss Americana & the Heartbreak Prince",
    "Paper Rings",
    "Cornelia Street",
    "Death by a Thousand Cuts",
    "London Boy",
    "Soon You'll Get Better",
    "False God",
    "You Need to Calm Down",
    "Afterglow",
    "Me!",
    "It's Nice to Have a Friend",
    "Daylight",
    "Fearless",
    "Fifteen",
    "Love Story",
    "Hey Stephen",
    "White Horse",
    "You Belong With Me",
    "Breathe",
    "Tell Me Why",
    "You're Not Sorry",
    "The Way I Loved You",
    "The Best Day",
    "Back to December",
    "Speak Now",
    "Dear John",
    "Mean",
    "The Story of Us",
    "Never Grow Up",
    "Enchanted",
    "Better Than Revenge",
    "Innocent",
    "Haunted",
    "Last Kiss",
    "Long Live",
    "Ours",
    "If This Was a Movie",
    "Superman",
    "Welcome To New York",
    "Blank Space",
    "Style",
    "Out Of The Woods",
    "All You Had To Do Was Stay",
    "Shake It Off",
    "I Wish You Would",
    "Bad Blood",
    "Wildest Dreams",
    "How You Get The Girl",
    "This Love",
    "I Know Places",
    "Clean",
    "the 1",
    "cardigan",
    "the last great american dynasty",
    "exile",
    "my tears ricochet",
    "mirrorball",
    "seven",
    "august",
    "this is me trying",
    "illicit affairs",
    "invisible string",
    "mad woman",
    "epiphany",
    "betty",
    "peace",
    "hoax",
    "State of Grace",
    "Red",
    "Treacherous",
    "I Knew You Were Trouble",
    "All Too Well",
    "22",
    "I Almost Do",
    "We Are Never Ever Getting Back Together",
    "Stay Stay Stay",
    "The Last Time",
    "Holy Ground",
    "Sad Beautiful Tragic",
    "The Lucky One",
    "Everything Has Changed",
    "Starlight",
    "Begin Again",
]

export default taylorSongs;